services:
  mermaidlive-ssr:
    build:
      context: mermaidlive_ssr
      dockerfile: Dockerfile
    hostname: mermaidlive-ssr.internal
    ports:
      - "10010:10010"
    environment:
      # mix phx.gen.secret 64
      - SECRET_KEY_BASE=$${SECRET_KEY_BASE:local-mvdFQorfNMybRBcmId3ChnRv6lzbjZRWcckMal4seVrf+4/3/dZ3dhiU7XMgESAE}
      - RELEASE_COOKIE=local-ICxIaPh1M
      - LOG_LEVEL=debug
      - PORT=10010
