# fly.toml app configuration file generated for mermaid-server on 2025-05-06T17:41:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mermaid-server'
primary_region = 'ams'

[build]
  image = 'tomwright/mermaid-server:latest'

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  # processes = ['app']

  [http_service.concurrency]
    type = "requests"
    # Fly Proxy uses this limit to determine Machine excess capacity
    soft_limit = 250

[[vm]]
  size = 'shared-cpu-1x'
