#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "rendering state '$state' into '$output'"

cd "$SCRIPT_DIR"

mkdir -p output

echo "$input" | mmdc -o "$output" -i -
