#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

graph='stateDiagram-v2
      [*] --> waiting
      waiting --> working : start
      working --> aborting : abort
      working --> waiting
      aborting --> waiting
'

curl --location --request POST 'http://localhost:10011/generate' \
--header 'Content-Type: text/plain' \
--data-raw "$graph"
